spring:
#  datasource:
#    url: jdbc:mysql://localhost/shop?characterEncoding=utf8
#    username: shopuser
#    password: shoppass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    open-in-view: false

logging:
  level:
    root: INFO
    me.hoonti06.osiv: DEBUG
    org.springframework.security: DEBUG