POST http://localhost:8080/orders/order
Content-Type: application/json

{
  "orderProducts": [
    {
      "productId": "prod-001",
      "quantity": 3
    },
    {
      "productId": "prod-002",
      "quantity": 2
    }
  ],
  "ordererMemberId": "1",
  "shippingInfo": {
    "address": {
      "zipCode": "12345",
      "address1": "Seoul",
      "address2": "Gangnam"
    },
    "message" : "hi",
    "receiver": {
      "name": "hoon",
      "phone": "010-0000-0000"
    }
  }
}